---

- name: Install mysql backup pre/post hook action files
  with_items: '{{ automysqlbackup_hook_files }}'
  copy: |
    src='{{ item.src }}'
    dest='{{ item.dest }}'
    owner=root
    group=root
    mode=0550
